//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deskVideoClub.clienteVideoClub {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Alquiler[] AlquilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.usuario[] usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Alquiler[] Alquiler {
            get {
                return this.AlquilerField;
            }
            set {
                if ((object.ReferenceEquals(this.AlquilerField, value) != true)) {
                    this.AlquilerField = value;
                    this.RaisePropertyChanged("Alquiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoE {
            get {
                return this.CorreoEField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEField, value) != true)) {
                    this.CorreoEField = value;
                    this.RaisePropertyChanged("CorreoE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNac {
            get {
                return this.FechaNacField;
            }
            set {
                if ((this.FechaNacField.Equals(value) != true)) {
                    this.FechaNacField = value;
                    this.RaisePropertyChanged("FechaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEmpleadoField, value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.usuario[] usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alquiler", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Alquiler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarnetSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Empleado EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Socio SocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.detAlquiler[] detAlquilerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarnetSocio {
            get {
                return this.CarnetSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.CarnetSocioField, value) != true)) {
                    this.CarnetSocioField = value;
                    this.RaisePropertyChanged("CarnetSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dias {
            get {
                return this.DiasField;
            }
            set {
                if ((this.DiasField.Equals(value) != true)) {
                    this.DiasField = value;
                    this.RaisePropertyChanged("Dias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Empleado Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Socio Socio {
            get {
                return this.SocioField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioField, value) != true)) {
                    this.SocioField = value;
                    this.RaisePropertyChanged("Socio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMovimiento {
            get {
                return this.TipoMovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMovimientoField, value) != true)) {
                    this.TipoMovimientoField = value;
                    this.RaisePropertyChanged("TipoMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.detAlquiler[] detAlquiler {
            get {
                return this.detAlquilerField;
            }
            set {
                if ((object.ReferenceEquals(this.detAlquilerField, value) != true)) {
                    this.detAlquilerField = value;
                    this.RaisePropertyChanged("detAlquiler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Empleado EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoUsrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Empleado Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmp {
            get {
                return this.IdEmpField;
            }
            set {
                if ((this.IdEmpField.Equals(value) != true)) {
                    this.IdEmpField = value;
                    this.RaisePropertyChanged("IdEmp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoUsr {
            get {
                return this.codigoUsrField;
            }
            set {
                if ((this.codigoUsrField.Equals(value) != true)) {
                    this.codigoUsrField = value;
                    this.RaisePropertyChanged("codigoUsr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passw {
            get {
                return this.passwField;
            }
            set {
                if ((object.ReferenceEquals(this.passwField, value) != true)) {
                    this.passwField = value;
                    this.RaisePropertyChanged("passw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Socio", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Socio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Alquiler[] AlquilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Alquiler[] Alquiler {
            get {
                return this.AlquilerField;
            }
            set {
                if ((object.ReferenceEquals(this.AlquilerField, value) != true)) {
                    this.AlquilerField = value;
                    this.RaisePropertyChanged("Alquiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Carnet {
            get {
                return this.CarnetField;
            }
            set {
                if ((object.ReferenceEquals(this.CarnetField, value) != true)) {
                    this.CarnetField = value;
                    this.RaisePropertyChanged("Carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoE {
            get {
                return this.CorreoEField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEField, value) != true)) {
                    this.CorreoEField = value;
                    this.RaisePropertyChanged("CorreoE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNac {
            get {
                return this.FechaNacField;
            }
            set {
                if ((this.FechaNacField.Equals(value) != true)) {
                    this.FechaNacField = value;
                    this.RaisePropertyChanged("FechaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSocio {
            get {
                return this.IdSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSocioField, value) != true)) {
                    this.IdSocioField = value;
                    this.RaisePropertyChanged("IdSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="detAlquiler", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class detAlquiler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Alquiler AlquilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlquilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPeliculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.Pelicula PeliculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Alquiler Alquiler {
            get {
                return this.AlquilerField;
            }
            set {
                if ((object.ReferenceEquals(this.AlquilerField, value) != true)) {
                    this.AlquilerField = value;
                    this.RaisePropertyChanged("Alquiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlquiler {
            get {
                return this.IdAlquilerField;
            }
            set {
                if ((this.IdAlquilerField.Equals(value) != true)) {
                    this.IdAlquilerField = value;
                    this.RaisePropertyChanged("IdAlquiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetalle {
            get {
                return this.IdDetalleField;
            }
            set {
                if ((this.IdDetalleField.Equals(value) != true)) {
                    this.IdDetalleField = value;
                    this.RaisePropertyChanged("IdDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPelicula {
            get {
                return this.IdPeliculaField;
            }
            set {
                if ((this.IdPeliculaField.Equals(value) != true)) {
                    this.IdPeliculaField = value;
                    this.RaisePropertyChanged("IdPelicula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.Pelicula Pelicula {
            get {
                return this.PeliculaField;
            }
            set {
                if ((object.ReferenceEquals(this.PeliculaField, value) != true)) {
                    this.PeliculaField = value;
                    this.RaisePropertyChanged("Pelicula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pelicula", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Pelicula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private deskVideoClub.clienteVideoClub.detAlquiler[] detAlquilerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deskVideoClub.clienteVideoClub.detAlquiler[] detAlquiler {
            get {
                return this.detAlquilerField;
            }
            set {
                if ((object.ReferenceEquals(this.detAlquilerField, value) != true)) {
                    this.detAlquilerField = value;
                    this.RaisePropertyChanged("detAlquiler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="clienteVideoClub.IsrvEmpleado")]
    public interface IsrvEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleados", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadosResponse")]
        deskVideoClub.clienteVideoClub.Empleado[] ListarEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleados", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadosResponse")]
        System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado[]> ListarEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadoResponse")]
        deskVideoClub.clienteVideoClub.Empleado ListarEmpleado(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadoResponse")]
        System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado> ListarEmpleadoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleadosNom", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadosNomResponse")]
        deskVideoClub.clienteVideoClub.Empleado[] ListarEmpleadosNom(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleadosNom", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadosNomResponse")]
        System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado[]> ListarEmpleadosNomAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/NuevoEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/NuevoEmpleadoResponse")]
        string NuevoEmpleado(deskVideoClub.clienteVideoClub.Empleado emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/NuevoEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/NuevoEmpleadoResponse")]
        System.Threading.Tasks.Task<string> NuevoEmpleadoAsync(deskVideoClub.clienteVideoClub.Empleado emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ModificarEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/ModificarEmpleadoResponse")]
        string ModificarEmpleado(deskVideoClub.clienteVideoClub.Empleado emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ModificarEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/ModificarEmpleadoResponse")]
        System.Threading.Tasks.Task<string> ModificarEmpleadoAsync(deskVideoClub.clienteVideoClub.Empleado emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/EliminarEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/EliminarEmpleadoResponse")]
        string EliminarEmpleado(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/EliminarEmpleado", ReplyAction="http://tempuri.org/IsrvEmpleado/EliminarEmpleadoResponse")]
        System.Threading.Tasks.Task<string> EliminarEmpleadoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleadoFechaNac", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadoFechaNacResponse")]
        deskVideoClub.clienteVideoClub.Empleado[] ListarEmpleadoFechaNac(System.DateTime fechDesde, System.DateTime fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEmpleado/ListarEmpleadoFechaNac", ReplyAction="http://tempuri.org/IsrvEmpleado/ListarEmpleadoFechaNacResponse")]
        System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado[]> ListarEmpleadoFechaNacAsync(System.DateTime fechDesde, System.DateTime fechaHasta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvEmpleadoChannel : deskVideoClub.clienteVideoClub.IsrvEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvEmpleadoClient : System.ServiceModel.ClientBase<deskVideoClub.clienteVideoClub.IsrvEmpleado>, deskVideoClub.clienteVideoClub.IsrvEmpleado {
        
        public IsrvEmpleadoClient() {
        }
        
        public IsrvEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public deskVideoClub.clienteVideoClub.Empleado[] ListarEmpleados() {
            return base.Channel.ListarEmpleados();
        }
        
        public System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado[]> ListarEmpleadosAsync() {
            return base.Channel.ListarEmpleadosAsync();
        }
        
        public deskVideoClub.clienteVideoClub.Empleado ListarEmpleado(int Id) {
            return base.Channel.ListarEmpleado(Id);
        }
        
        public System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado> ListarEmpleadoAsync(int Id) {
            return base.Channel.ListarEmpleadoAsync(Id);
        }
        
        public deskVideoClub.clienteVideoClub.Empleado[] ListarEmpleadosNom(string nombre) {
            return base.Channel.ListarEmpleadosNom(nombre);
        }
        
        public System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado[]> ListarEmpleadosNomAsync(string nombre) {
            return base.Channel.ListarEmpleadosNomAsync(nombre);
        }
        
        public string NuevoEmpleado(deskVideoClub.clienteVideoClub.Empleado emp) {
            return base.Channel.NuevoEmpleado(emp);
        }
        
        public System.Threading.Tasks.Task<string> NuevoEmpleadoAsync(deskVideoClub.clienteVideoClub.Empleado emp) {
            return base.Channel.NuevoEmpleadoAsync(emp);
        }
        
        public string ModificarEmpleado(deskVideoClub.clienteVideoClub.Empleado emp) {
            return base.Channel.ModificarEmpleado(emp);
        }
        
        public System.Threading.Tasks.Task<string> ModificarEmpleadoAsync(deskVideoClub.clienteVideoClub.Empleado emp) {
            return base.Channel.ModificarEmpleadoAsync(emp);
        }
        
        public string EliminarEmpleado(int Id) {
            return base.Channel.EliminarEmpleado(Id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarEmpleadoAsync(int Id) {
            return base.Channel.EliminarEmpleadoAsync(Id);
        }
        
        public deskVideoClub.clienteVideoClub.Empleado[] ListarEmpleadoFechaNac(System.DateTime fechDesde, System.DateTime fechaHasta) {
            return base.Channel.ListarEmpleadoFechaNac(fechDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<deskVideoClub.clienteVideoClub.Empleado[]> ListarEmpleadoFechaNacAsync(System.DateTime fechDesde, System.DateTime fechaHasta) {
            return base.Channel.ListarEmpleadoFechaNacAsync(fechDesde, fechaHasta);
        }
    }
}
