//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class detAlquiler
    {
        public int IdDetalle { get; set; }
        public int IdAlquiler { get; set; }
        public int IdPelicula { get; set; }
        public decimal precio { get; set; }
        public string Estado { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
        public virtual Pelicula Pelicula { get; set; }
    }
}
