//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigoUsr { get; set; }
        public int IdEmp { get; set; }
        public string rol { get; set; }
        public string passw { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
